version: '3.6'

services:
  # api:
  #   build: ./api
  #   volumes:
  #     - ./api:/app
  #   ports:
  #     - 5000:3000
  #   depends_on:
  #     - db
  #     - redis
  #   environment:
  #     DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:10.3-alpine
    volumes:
      - jobsity-postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    volumes:
      - jobsity-redis-volume:/data
    ports:
      - 6379:6379
volumes:
  jobsity-postgres-volume:
  jobsity-redis-volume: